(() => {
'use strict';
const M=TaxMarket, $=id=>document.getElementById(id), lecture=document.body.dataset.mode==='lecture';
const fixed=M.market(4), base=M.market(0), P=M.practiceAccount(), money=n=>'$'+n.toFixed(2);
const names=['Start with the trades','Who still trades?','Understand the gains from trade','Explain what changed','Test a smaller tax','A fresh case'];
function feedback(id,text,good){$(id).textContent=text;$(id).className='feedback '+(good?'good':'retry');}
function stage(n){document.querySelectorAll('section[id^=stage]').forEach(s=>s.hidden=s.id!==`stage-${n}`);$('progress').textContent=`${n+1} of ${lecture?4:6} · ${names[n]}`;const h=$(`stage-${n}`).querySelector('h2');h.focus();h.scrollIntoView({block:'start'});}
function table(rows,headers,caption){return `<table><caption>${caption}</caption><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>i===0?`<th scope="row">${v}</th>`:`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
$('schedule').innerHTML=table(base.rows.map(r=>[r.unit,money(r.value),money(r.cost)]),['Repair','Buyer value (WTP)','Seller cost'],'The four possible repairs');
$('lecture-end').hidden=!lecture;$('practice-next').hidden=lecture;
$('baseline').addEventListener('submit',e=>{e.preventDefault();const a=new FormData(e.target).get('count');if(a===null){feedback('baseline-feedback','Choose how many repairs occur first.',false);return;}TaxMetrics.milestone('activity_start');feedback('baseline-feedback',`${a==='4'?'Yes.':'Compare both sides.'} All four buyer values (WTP) exceed ${money(base.buyer)}, and all four costs are below ${money(base.seller)}. ${base.trades} repairs occur. Their total gains from trade (total surplus) are ${money(base.total)}.`,a==='4');$('to-tax').hidden=false;});
$('participants').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target), buyers=data.getAll('buyers').map(Number), sellers=data.getAll('sellers').map(Number);const correct=[buyers,sellers].every(a=>a.length===2&&a.includes(0)&&a.includes(1));feedback('participants-feedback',correct?'Yes. The first two buyers and first two sellers trade. Two repairs occur.':'Buyer values $12 and $10 cover $8.50; $8 and $6 do not. Seller costs $2 and $4 are below $4.50; both $5 sellers sit out. Two buyers match two sellers, so two repairs occur.',correct);$('to-audit').hidden=false;});
$('audits').innerHTML=[fixed.rows[0],fixed.rows[2]].map(r=>`<div class="card"><h3>Repair ${r.unit}: ${r.traded?'still happens':'cancelled'}</h3><p>Buyer value (WTP): ${money(r.value)}<br>Seller cost: ${money(r.cost)}<br>Potential gains from trade: ${money(r.gain)} (${money(r.value)} − ${money(r.cost)})</p>${r.traded?`<ul><li>Buyer's consumer surplus: <strong>${money(r.cs)}</strong> (${money(r.value)} − ${money(fixed.buyer)}).</li><li>Seller's producer surplus: <strong>${money(r.ps)}</strong> (${money(fixed.seller)} − ${money(r.cost)}).</li><li>Government collects <strong>${money(r.revenue)}</strong> in tax revenue.</li></ul><p>Together, total surplus is <strong>${money(r.cs+r.ps+r.revenue)}</strong>, equal to the gains from this trade.</p>`:`<p>The buyer will not pay ${money(fixed.buyer)}, and the seller will not accept ${money(fixed.seller)}.</p><p>Consumer surplus and producer surplus are both $0. Government collects no tax revenue from this cancelled repair.</p><p>Its <strong>${money(r.gain)} in potential gains from trade are lost</strong>.</p>`}</div>`).join('');
$('potential-gains').innerHTML=table(fixed.rows.map(r=>[r.unit,money(r.value),money(r.cost),money(r.gain),r.traded?'Still happens':'Cancelled']),['Repair','Buyer value (WTP)','Seller cost','Potential gains from trade','Outcome'],'Find the lost gains from trade from the cancelled repairs');
function renderAccounts(){
 $('totals').innerHTML=[["Buyer's consumer surplus",fixed.cs],["Seller's producer surplus",fixed.ps],['Government tax revenue',fixed.revenue],['Deadweight loss',fixed.dwl]].map(([s,n])=>`<div>${s}<strong>${money(n)}</strong></div>`).join('');
 $('ledger').innerHTML=table(fixed.rows.map(r=>[r.unit,r.traded?'Still happens':'Cancelled',money(r.cs),money(r.ps),money(r.revenue),money(r.lost)]),['Repair','Outcome',"Buyer's consumer surplus","Seller's producer surplus",'Government tax revenue','Lost gains from trade'],'After the $4 tax: surplus, tax revenue and lost gains from trade');
 $('account-explanation').innerHTML=`<p><strong>Before-tax total surplus:</strong> ${money(base.cs)} consumer surplus + ${money(base.ps)} producer surplus = <strong>${money(base.total)}</strong>.</p><p><strong>After-tax total surplus:</strong> ${money(fixed.cs)} consumer surplus + ${money(fixed.ps)} producer surplus + ${money(fixed.revenue)} government tax revenue = <strong>${money(fixed.total)}</strong>.</p><p><strong>Deadweight loss:</strong> ${money(base.total)} − ${money(fixed.total)} = <strong>${money(fixed.dwl)}</strong>. These are the lost gains from trade from cancelled repairs 3 and 4. The ${money(fixed.revenue)} in tax revenue is a transfer to government, not deadweight loss.</p>`;
}
renderAccounts();
$('loss').addEventListener('submit',e=>{
 e.preventDefault(); const n=Number($('lost-prediction').value);
 const cancelled=fixed.rows.filter(r=>!r.traded);
 const lostDetails=cancelled.map(r=>`repair ${r.unit} loses ${money(r.lost)}`).join(', and ');
 const explanation=`Two repairs are cancelled: ${lostDetails}. These lost gains from trade total ${money(fixed.dwl)} and are the deadweight loss. Two repairs still happen, so government collects ${money(fixed.revenue)} in tax revenue. That revenue is a transfer, not a loss of gains from trade.`;
 const prefix=n===fixed.dwl?'Yes. ':n===fixed.revenue?`${money(fixed.revenue)} is government tax revenue, not deadweight loss. `:n===base.cs+base.ps-fixed.cs-fixed.ps?`The ${money(n)} decrease in consumer surplus plus producer surplus includes ${money(fixed.revenue)} transferred to government. `:'Count the gains from the cancelled repairs. ';
 feedback('loss-feedback',prefix+explanation,n===fixed.dwl);$('accounts').hidden=false;
});
for(const [from,to] of [['to-tax',1],['to-audit',2],['to-explain',3]]) $(from).addEventListener('click',()=>{stage(to);if(lecture&&to===3)TaxMetrics.milestone('activity_complete');});

if(!lecture){
 $('boundary-schedule').innerHTML=$('schedule').innerHTML;
 $('to-boundary').addEventListener('click',()=>stage(4));
 $('boundary').addEventListener('submit',e=>{e.preventDefault();const a=new FormData(e.target).get('boundary');if(!a){feedback('boundary-feedback','Choose a prediction first.',false);return;}const small=M.market(.5);feedback('boundary-feedback',a==='same'?'Yes. All four buyers and sellers still trade. Revenue is $2 and deadweight loss is $0.':'A positive tax need not cancel a trade. All four values still exceed $5.75 and all four costs are below $5.25. Revenue is $2; deadweight loss is $0.',a==='same');$('boundary-table').innerHTML=table([base,small,fixed].map(r=>[money(r.tax),r.trades,money(r.cs),money(r.ps),money(r.revenue),money(r.total),money(r.dwl)]),['Tax','Repairs',"Buyer's consumer surplus","Seller's producer surplus",'Government tax revenue','Total surplus','Deadweight loss'],'Compare three valid clearing-price settings');$('boundary-result').hidden=false;});
 $('to-practice').addEventListener('click',()=>stage(5));
 $('practice').addEventListener('submit',e=>{e.preventDefault();const a=new FormData(e.target).get('practice');if(!a){feedback('practice-feedback','Choose an argument first.',false);return;}feedback('practice-feedback',a==='missing'?`Yes. The first mug still adds ${money(P.gain)}: consumer surplus ${money(P.cs)} + producer surplus ${money(P.ps)} + tax revenue ${money(P.revenue)}. The cancelled second mug loses gains from trade of ${money(P.values[1])} minus ${money(P.costs[1])} = ${money(P.lost)}.`:a==='revenue'?`Government collects ${money(P.revenue)} in tax revenue on the first sale. Its ${money(P.gain)} in gains from trade survives, split three ways. The second sale would have added ${money(P.lost)}, and those gains from trade are lost.`:`Transfers alone do not destroy gains, but a cancelled beneficial sale does lose gains from trade. The second mug would have added ${money(P.values[1])} minus ${money(P.costs[1])} = ${money(P.lost)}. No tax is collected on that sale.`,a==='missing');$('finish-practice').hidden=false;});
 $('finish-practice').addEventListener('click',()=>{$('practice-complete').hidden=false;TaxMetrics.milestone('activity_complete');});
}
// Changed choices clear stale feedback and require a fresh check; correctness is not a progression gate.
for(const [form,fb,next] of [['baseline','baseline-feedback','to-tax'],['participants','participants-feedback','to-audit'],['loss','loss-feedback','accounts'],...(!lecture?[['boundary','boundary-feedback','boundary-result'],['practice','practice-feedback','finish-practice']]:[])]){
 $(form).addEventListener('input',()=>{$(fb).textContent='Check your revised answer to see feedback.';$(fb).className='feedback';$(next).hidden=true;if(form==='practice')$('practice-complete').hidden=true;});
}
$('large').addEventListener('click',()=>{const on=document.documentElement.classList.toggle('large');$('large').setAttribute('aria-pressed',String(on));});
$('restart').addEventListener('click',()=>{document.querySelectorAll('form').forEach(f=>f.reset());document.querySelectorAll('.feedback').forEach(f=>{f.textContent='Choose an answer, then check it. There is no penalty for trying again.';f.className='feedback';});['to-tax','to-audit','accounts',...(!lecture?['boundary-result','finish-practice','practice-complete']:[])].forEach(id=>$(id).hidden=true);document.querySelectorAll('details').forEach(d=>d.open=false);TaxMetrics.reset();stage(0);});
document.querySelectorAll('button').forEach(b=>b.disabled=false);
})();
